USE customer_behaviour_analysis;
Select * from customer;

-- 1. What is the total revenue generated by male and female customers?
select gender, sum(purchase_amount)
from customer
group by gender;

-- 2. Which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount, discount_applied
from customer
where purchase_amount > (select avg(purchase_amount) from customer) and discount_applied = 'Yes';

-- 3. Which are the top 5 products with the highest AVERAGE review rating?
select item_purchased, round(avg(review_rating),2) as 'Average Review'
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. Compare the average purchase amounts between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- 5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.
select 
	case 
		when subscription_status = 'Yes' Then 'Subscribed'
		when subscription_status = 'No' Then 'Non-subscribed'
    end as subscription_status,
	sum(purchase_amount) as 'total_revenue', 
	avg(purchase_amount) as 'average_spend',
	count(customer_id) as 'total_customer'
from customer
group by subscription_status
order by total_revenue, average_spend desc;

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
 select item_purchased,
	sum((case when discount_applied = 'Yes' Then 1 Else 0 end))*100/count(*) as purchase_rate
from customer
group by item_purchased
order by purchase_rate desc
limit 5;

-- 7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
	select customer_id, previous_purchases,
    case 
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
	end as customer_segment
    from customer
)
select customer_segment, count(*) as 'number of customers'
from customer_type
group by customer_segment;

-- 8. What are the top 3 most purchased products within each category? 
select * from customer;
-- Created a CTE and a column called item_rank where the rank refreshes every time new category comes.
with item_counts as (
	select category, item_purchased, count(customer_id) as total_orders,
    -- rank refresh is partitioned by category and sorted them in descending order. 
    row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from customer
    group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select * from customer;
select subscription_status, count(customer_id) as 'repeated_buyers'
from customer
where previous_purchases > 5
group by subscription_status
order by repeated_buyers;

-- 10. What is the revenue contribution of each age group? 
select * from customer;
select age_group, sum(purchase_amount) as 'revenue'
from customer
group by age_group
order by revenue desc;